using System;
using System.Runtime.InteropServices;

namespace IMAPI2.Interop
{
	public enum IMAPI_FORMAT2_TAO_WRITE_ACTION
	{
		[TypeLibVar(64)]
		IMAPI_FORMAT2_TAO_WRITE_ACTION_UNKNOWN,
		IMAPI_FORMAT2_TAO_WRITE_ACTION_PREPARING,
		IMAPI_FORMAT2_TAO_WRITE_ACTION_WRITING,
		IMAPI_FORMAT2_TAO_WRITE_ACTION_FINISHING,
		IMAPI_FORMAT2_TAO_WRITE_ACTION_VERIFYING
	}
}